services:
  postgres-app:
    container_name: postgres-app-product
    image: postgres:15
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: product_db
    ports:
      - "5432:5432"
    networks:
      - mynet
    volumes:
      - postgres_app:/var/lib/postgresql/data
      - ./data-sample.sql:/docker-entrypoint-initdb.d/init.sql
    
  adminer:
    image: adminer:5.4.1
    ports:
      - "8081:8080"
    depends_on:
     - postgres-app
    networks:
      - mynet

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: spring-api
    ports:
      - "8080:8080"
    networks:
      - mynet
    depends_on: 
      - postgres-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-app:5432/product_db
      SPRING_DATASOURCE_USERNAME: username
      SPRING_DATASOURCE_PASSWORD: password

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-ui
    ports:
      - "3000:80" 
    networks:
      - mynet
    depends_on:
      - backend
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf

  k6:
    image: grafana/k6:latest
    volumes:
      - ./backend/performance:/scripts
    working_dir: /scripts
    entrypoint: ["bash", "-c"]
    command: ["k6 run login-test.js"]
    depends_on:
      - backend
    networks:
      - mynet

networks:
  mynet:

volumes:
  postgres_app:
